### ISSUE TITLE
Logging interceptor breaks downloading pdf file

### ISSUE THREAD

**Issue by reisub** [ihsanbal/LoggingInterceptor#14]
Using this interceptor breaks pdf download for me.

The usage is simple, I have a direct link to a pdf file which I download with Retrofit and write into a file. The original pdf has around 199kb, however the downloaded file has around 350kb.

I debugged into the issue and I think the problem is in this line:
https://github.com/ihsanbal/LoggingInterceptor/blob/master/library/src/main/java/com/ihsanbal/logging/LoggingInterceptor.java#L70

This line sets the response body content type to the same content type that the request body has which is not correct behavior. In this case, the request body is `application/json` and the response body is `application/pdf`. As a result, the pdf gets downloaded with the wrong encoding and it results in a corrupt file.

Another problem I see is that the interceptor will reformat the body before passing it on which is just asking for problems. The interceptor should pass the original body down the interceptor chain and reformat just for display. It doesn't even check the content type to see if the body is in fact json.

**Comment by ihsanbal** [comment]
@reisub Thanks for your help! I will fix this two bug as soon as possible.

**Comment by ihsanbal** [comment]
@reisub Release candidate available with [1.0-rc6](https://github.com/ihsanbal/LoggingInterceptor#download) tag.

**Comment by reisub** [comment]
Verified and working,.

**Comment by ihsanbal** [comment]
@reisub I reopened this issue for check content-type is null or not.
