### ISSUE TITLE
Warning in gradle messages when using 2.0.0

### ISSUE THREAD

**Issue by lolsheeplol** [ihsanbal/LoggingInterceptor#21]
Hi, 

Just thought I'd let you know, on my project when I bump LoggingInterceptor from 1.0.4 to 2.0.0 my gradle compiles successfully but warns about these lines: 

`Warning:WARNING: Dependency org.json:json:20160810 is ignored for prodDebug as it may be conflicting with the internal version provided by Android.`
`Warning:WARNING: Dependency org.json:json:20160810 is ignored for prodRelease as it may be conflicting with the internal version provided by Android.`
`Warning:WARNING: Dependency org.json:json:20160810 is ignored for fastdevDebug as it may be conflicting with the internal version provided by Android.`
`Warning:WARNING: Dependency org.json:json:20160810 is ignored for fastdevRelease as it may be conflicting with the internal version provided by Android.`

Any insight into what's happening here?  It's warned for each flavor I have, and it seems like maybe you're bundling a `org.json:json` dependency that is usually provided by the Android sdk.

**Comment by lolsheeplol** [comment]
Hmm, okay so I went back to the readme and conclude that I'm just bad at reading.  I forgot to include the **exclude group: 'org.json', module: 'json'** part.  Any reason why it needs to be excluded?

**Comment by ihsanbal** [comment]
The answer is hidden in your log: `it may be conflicting with the internal version provided by Android`.

**Comment by lolsheeplol** [comment]
Good to know.  Thanks for putting out this library!
