### ISSUE TITLE
 java.lang.ClassCastException: java.lang.String cannot be cast to okhttp3.Request

### ISSUE THREAD

**Issue by OneOfBillions** [ihsanbal/LoggingInterceptor#23]
[com.ihsanbal.logging.LoggingInterceptor.intercept(LoggingInterceptor.java:75), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), com.tianxiang.client.utils.net.core.OkHttpNetEngine$OkHttpExcutor.requestByMethod(OkHttpNetEngine.java:222), com.tianxiang.client.utils.net.core.OkHttpNetEngine.request(OkHttpNetEngine.java:274), com.tianxiang.client.utils.net.task.CommonNetTask.run(CommonNetTask.java:49), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:818)]

**Comment by ihsanbal** [comment]
Can you share your code? @OneOfBillions

**Comment by OneOfBillions** [comment]
Request.Builder builder = new Request.Builder();
            if (taskTag != null) {
                builder.tag(taskTag);
            }
