### ISSUE TITLE
Lack of synchronization mechanism 

### ISSUE THREAD

**Issue by OneOfBillions** [ihsanbal/LoggingInterceptor#24]
╚═══════════════════════════════════════════════════════════════════════════════════════
I/OkHttpNetEngine: ╔══════ Response ═══════════════════════════════════════════════════════════════════════
I/OkHttpNetEngine: ╔══════ Response ═══════════════════════════════════════════════════════════════════════
I/OkHttpNetEngine: ╔══════ Response ═══════════════════════════════════════════════════════════════════════
I/OkHttpNetEngine: ╔══════ Response ═══════════════════════════════════════════════════════════════════════
I/OkHttpNetEngine: ╔══════ Response ═══════════════════════════════════════════════════════════════════════
I/OkHttpNetEngine: ║ /api/Client/My - is success : true - Received in: 89ms
I/OkHttpNetEngine: ║ /api/Client/ClientUser/My - is success : true - Received in: 111ms
I/OkHttpNetEngine: ║ /api/Client/Message/GetUnReadCount - is success : true - Received in: 172ms
I/OkHttpNetEngine: ║ 
I/OkHttpNetEngine: ║

**Comment by ihsanbal** [comment]
You can try to do this 

> https://github.com/ihsanbal/LoggingInterceptor#notes
