### ISSUE TITLE
I can't set my own tag

### ISSUE THREAD

**Issue by zzh1026** [ihsanbal/LoggingInterceptor#29]
In the 2.0.1 version, lines 71 and 72 have the following code:
     `Response response = chain.proceed(request);
     List segmentList = ((Request)request.tag()).url().encodedPathSegments();`
I took my url from the tag, but I set the url myself, So a ClassCastException occurs when used,I need to set up my own tag to cancel the request at any time through this tag

**Comment by ihsanbal** [comment]
Can you share your code? @zzh1026
