### ISSUE TITLE
Border beauty removal request : Suggestion

### ISSUE THREAD

**Issue by Qamar4P** [ihsanbal/LoggingInterceptor#30]
If you remove border so that developers can copy pretty json response and easily convert it to pojo. and upload it on maven central. thanks

**Comment by mrArtCore** [comment]
Please don’t. You can easily copy all you need with holding of scroll wheel on mouse and moving mouse in needed direction. After, when all needed lines has blinked coursors use hot keys combinations to select rows to end (shift+home or something like that)

**Comment by Qamar4P** [comment]
@mrArtCore  and some may like it so you can add configs just few if else inside.
I'm looking it like extra cream on pretty girl face.

**Comment by ihsanbal** [comment]
@Qamar4P 

- Mouse: Alt+MouseDrag
- Mac : Cmd+Shift+8
- Windows/Linux: Shift+Alt+Insert﻿
