### ISSUE TITLE
URL address in Response log

### ISSUE THREAD

**Issue by mrArtCore** [ihsanbal/LoggingInterceptor#37]
Hello @ihsanbal !!! 
We`ve been using your library for a while in our android team and we really like it =)) 
But sometimes we got in unconvinient situations, when we're having couple request before responses. For example,  lets say we are have to make 3-5 net requests in a same time. And then we get 3-5 reordered responses back and sometimes it's not very easy to find out which response belongs to which request. 

I have investigated your interceptor code and think  that I can add this feature. BTW I saw an open issue (#33) about that. 

Don't you mind if your library have this functional ? Would be such PR welcomed ?

**Comment by ihsanbal** [comment]
Yeah! I know multiple network threads hard to read at logcat but now I just moved-in new home and new country so if I can get a break in this complicated move-in life I will contribute about issue #33 but Your contributions are always a priority :)

**Comment by mrArtCore** [comment]
Okay )) Yeah. I`ve got some troubles with free time too =) 
So I'll drop a line, when I start to work with this feature.

**Comment by mrArtCore** [comment]
Hi @ihsanbal. I've started to work on this issue and just want make sure you don't =))

**Comment by ihsanbal** [comment]
No I don't :) I am waiting your pr. @mrArtCore

**Comment by mrArtCore** [comment]
fixed with 0b2b8157fb
