### ISSUE TITLE
Logging body!

### ISSUE THREAD

**Issue by khaledkhj** [ihsanbal/LoggingInterceptor#39]
Thanks a lot for such a great library.

It would be really really nice if we can see request data (Body Data)!

**Comment by alyadins** [comment]
` private static String[] getRequest(Request request, Level level) {
        String header = request.headers().toString();
        boolean loggableHeader = level == Level.HEADERS || level == Level.BASIC;
        String log = "Method: @" + request.method() + DOUBLE_SEPARATOR + (isEmpty(header)?"":(loggableHeader?"Headers:" + LINE_SEPARATOR + dotHeaders(header):""));
        return log.split(LINE_SEPARATOR);
    }`

Problem is here.

**Comment by ihsanbal** [comment]
#41
