### ISSUE TITLE
header add Twice Error

### ISSUE THREAD

**Issue by jinyulei0710** [ihsanbal/LoggingInterceptor#47]
when I use this interceptor to log,The same Header showed twice.

**Comment by jinyulei0710** [comment]
Headers headers = request.headers();
            Set<String> names = headers.names();
            Iterator<String> iterator = names.iterator();
            Request.Builder requestBuilder = request.newBuilder();
            for (String key : headerMap.keySet()) {
                String value = headerMap.get(key);
                requestBuilder.addHeader(key, value);
            }
            while (iterator.hasNext()) {
                String name = iterator.next();
                requestBuilder.addHeader(name, headers.get(name));
            }

**Comment by jinyulei0710** [comment]
@ihsanbal why you add header twice？

**Comment by orcchg** [comment]
Same to me. Headers are duplicating.

I had fallen back to 2.0.2

**Comment by orcchg** [comment]
```@Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        HashMap<String, String> headerMap = builder.getHeaders();
        if (headerMap.size() > 0) {
            Headers headers = request.headers();
            Set<String> names = headers.names();
            Iterator<String> iterator = names.iterator();
            Request.Builder requestBuilder = request.newBuilder();
            for (String key : headerMap.keySet()) {
                String value = headerMap.get(key);
                requestBuilder.addHeader(key, value);
            }
            while (iterator.hasNext()) {
                String name = iterator.next();
                requestBuilder.addHeader(name, headers.get(name));
            }
            request = requestBuilder.build();
}```

**Comment by ihsanbal** [comment]
I am going to solve this problem ASAP. Thanks for reporting.
