### ISSUE TITLE
2.0.5 build on jitpack is broken and can't be fetched

### ISSUE THREAD

**Issue by vararg** [ihsanbal/LoggingInterceptor#56]
2.0.5 build on jitpack is broken and can't be fetched
Please check it here https://jitpack.io/#ihsanbal/LoggingInterceptor

**Comment by LeeGeonho** [comment]
same

**Comment by MohMah** [comment]
same

**Comment by MohMah** [comment]
https://jitpack.io/com/github/ihsanbal/LoggingInterceptor/2.0.5/build.log

**Comment by MohMah** [comment]
See here: https://jitpack.io/#ihsanbal/LoggingInterceptor

**Comment by ihsanbal** [comment]
Greater versions are available like 2.0.6 - 3.0.0 with fixes and improvements. Please use one of the greatest version.
