### ISSUE TITLE
Why is .addQueryParam("query", "0") in the readme?

### ISSUE THREAD

**Issue by z3ntu** [ihsanbal/LoggingInterceptor#60]
Hi, in the project I'm working on, somebody copied the usage of this library including the `.addQueryParam("query", "0")` statement which now broke because an API endpoint checked for allowed url parameters - and `query=0` isn't allowed - so it broke.

Any reason this is in the 'Usage' section of the readme (where blindly people copy-paste from)?

**Comment by ihsanbal** [comment]
@z3ntu .addQueryParam("query", "0") function in readme file is just sample which shows you that you can add query param to all your requests like apiKey and other default things. So you better to remove it if you don't need it.
