### ISSUE TITLE
http message style might be better

### ISSUE THREAD

**Issue by gfzy9876** [ihsanbal/LoggingInterceptor#72]
just like this:

GET /path

Header1: xxx
Header2: xxx
Header3: xxx
...

Body

/path code msg

Header1: xxx
Header2: xxx
Header3: xxx
...

Body

**Comment by Tetr0N** [comment]
> just like this:
> 
> GET /path
> 
> Header1: xxx
> Header2: xxx
> Header3: xxx
> ...
> 
> Body
> 
> 
> 
> 
> /path code msg
> 
> Header1: xxx
> Header2: xxx
> Header3: xxx
> ...
> 
> Body
>
