### ISSUE TITLE
Log both Headers AND Body?

### ISSUE THREAD

**Issue by andrewmunn** [ihsanbal/LoggingInterceptor#8]
Is there a way to log both the headers and body of requests and responses? Seems like it's one or the other right now.

I guess I could just add two loggers?

**Comment by ihsanbal** [comment]
```
client.addInterceptor(new LoggingInterceptor.Builder()
                .loggable(BuildConfig.DEBUG) // 
                .setLevel(Level.BASIC)
                .log(Log.DEBUG)
                .request("Request")
                .response("Response")
                .build());
```
Level.BASIC log both the your endpoint url with query params, request method, headers and body of request and response.
>      - URL
>      - Method
>      - Headers
>      - Body

**Comment by kevinvanmierlo** [comment]
@ihsanbal Maybe add some info about it in your readme. I would not expect BASIC to log everything. Great library by the way!
